// Code generated by swaggo/swag. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/load": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Start a manual FDA data load. Returns 409 if a load is already in progress.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Trigger a data load",
                "parameters": [
                    {
                        "description": "Load options",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.TriggerLoadRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/api.TriggerLoadResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/load/{loadID}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns checkpoint progress for a specific load operation.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Check load status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Load ID (UUID)",
                        "name": "loadID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.LoadStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ndc/search": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Full-text search across brand names, generic names, and manufacturers. Supports prefix matching.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Search drugs by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query (e.g. metformin)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ndc/stats": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns row counts, last load time, and data freshness.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Dataset statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.StatsResult"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ndc/{ndc}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Accepts any NDC format (hyphenated, unhyphenated, 2-segment, 3-segment). Returns product details with packages.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Look up a product by NDC code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "NDC code (e.g. 0002-1433, 0002-1433-61, 00021433)",
                        "name": "ndc",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.ProductResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/ndc/{ndc}/packages": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns all package configurations for a given product NDC.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "List packages for a product NDC",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product NDC (e.g. 0002-1433)",
                        "name": "ndc",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/openfda/ndc.json": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Drop-in replacement for the openFDA /drug/ndc.json endpoint. Returns identical response format. Supports openFDA search syntax (field:value, exact phrases, AND via +).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OpenFDA"
                ],
                "summary": "openFDA-compatible NDC search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "openFDA search query (e.g. brand_name:metformin, product_ndc:\\",
                        "name": "search",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Results per page (default 1, max 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Pagination offset",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OpenFDAResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.OpenFDAError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.OpenFDAError"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service health status and data freshness. Degrades to \"degraded\" when data is \u003e48 hours old. No authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CheckpointStatus": {
            "type": "object",
            "properties": {
                "dataset": {
                    "type": "string"
                },
                "duration_seconds": {
                    "type": "number"
                },
                "error": {
                    "type": "string"
                },
                "row_count": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "table": {
                    "type": "string"
                }
            }
        },
        "api.LoadStatusResponse": {
            "type": "object",
            "properties": {
                "checkpoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.CheckpointStatus"
                    }
                },
                "load_id": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.OpenFDAActiveIngredient": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "strength": {
                    "type": "string"
                }
            }
        },
        "api.OpenFDAError": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/api.OpenFDAErrorDetail"
                }
            }
        },
        "api.OpenFDAErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.OpenFDAMeta": {
            "type": "object",
            "properties": {
                "disclaimer": {
                    "type": "string"
                },
                "last_updated": {
                    "type": "string"
                },
                "license": {
                    "type": "string"
                },
                "results": {
                    "$ref": "#/definitions/api.OpenFDAPagination"
                },
                "terms": {
                    "type": "string"
                }
            }
        },
        "api.OpenFDANested": {
            "type": "object",
            "properties": {
                "is_original_packager": {
                    "type": "array",
                    "items": {
                        "type": "boolean"
                    }
                },
                "manufacturer_name": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rxcui": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "spl_set_id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "unii": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "upc": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.OpenFDAPackaging": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "marketing_start_date": {
                    "type": "string"
                },
                "package_ndc": {
                    "type": "string"
                },
                "sample": {
                    "type": "boolean"
                }
            }
        },
        "api.OpenFDAPagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "skip": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.OpenFDAProduct": {
            "type": "object",
            "properties": {
                "active_ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.OpenFDAActiveIngredient"
                    }
                },
                "application_number": {
                    "type": "string"
                },
                "brand_name": {
                    "type": "string"
                },
                "brand_name_base": {
                    "type": "string"
                },
                "dosage_form": {
                    "type": "string"
                },
                "finished": {
                    "type": "boolean"
                },
                "generic_name": {
                    "type": "string"
                },
                "labeler_name": {
                    "type": "string"
                },
                "marketing_category": {
                    "type": "string"
                },
                "marketing_start_date": {
                    "type": "string"
                },
                "openfda": {
                    "$ref": "#/definitions/api.OpenFDANested"
                },
                "packaging": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.OpenFDAPackaging"
                    }
                },
                "pharm_class": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "product_id": {
                    "type": "string"
                },
                "product_ndc": {
                    "type": "string"
                },
                "product_type": {
                    "type": "string"
                },
                "route": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "spl_id": {
                    "type": "string"
                }
            }
        },
        "api.OpenFDAResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/api.OpenFDAMeta"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.OpenFDAProduct"
                    }
                }
            }
        },
        "api.TriggerLoadRequest": {
            "type": "object",
            "properties": {
                "datasets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "force": {
                    "type": "boolean"
                }
            }
        },
        "api.TriggerLoadResponse": {
            "type": "object",
            "properties": {
                "datasets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "load_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "store.PackageResult": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "ndc": {
                    "type": "string"
                },
                "sample": {
                    "type": "boolean"
                }
            }
        },
        "store.ProductResult": {
            "type": "object",
            "properties": {
                "active_ingredients": {
                    "type": "string"
                },
                "application_number": {
                    "type": "string"
                },
                "brand_name": {
                    "type": "string"
                },
                "dea_schedule": {
                    "type": "string"
                },
                "dosage_form": {
                    "type": "string"
                },
                "generic_name": {
                    "type": "string"
                },
                "manufacturer": {
                    "type": "string"
                },
                "marketing_category": {
                    "type": "string"
                },
                "matched_package": {
                    "type": "string"
                },
                "packages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.PackageResult"
                    }
                },
                "pharm_classes": {
                    "type": "string"
                },
                "product_ndc": {
                    "type": "string"
                },
                "route": {
                    "type": "string"
                },
                "strength": {
                    "type": "string"
                },
                "strength_unit": {
                    "type": "string"
                }
            }
        },
        "store.StatsResult": {
            "type": "object",
            "properties": {
                "applications": {
                    "type": "integer"
                },
                "last_loaded": {
                    "type": "string"
                },
                "load_duration_seconds": {
                    "type": "number"
                },
                "packages": {
                    "type": "integer"
                },
                "products": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ndc-loader API",
	Description:      "FDA NDC Directory bulk loader and REST API. Ingests NDC Directory and Drugs@FDA datasets daily, serves via REST with full-text search and NDC format normalization.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
